# -*- coding: utf-8 -*-

BOT_NAME = 'capacitors'
SPIDER_MODULES = ['capacitors.spiders']
NEWSPIDER_MODULE = 'capacitors.spiders'

ROBOTSTXT_OBEY = True

DOWNLOADER_MIDDLEWARES = {
    'scrapy_crawlera.CrawleraMiddleware': 610
}

CRAWLERA_APIKEY = ''
DOWNLOAD_DELAY = 2
CRAWLERA_ENABLED = True
CONCURRENT_REQUESTS = 32
CONCURRENT_REQUESTS_PER_DOMAIN = 32
AUTOTHROTTLE_ENABLED = False
DOWNLOAD_TIMEOUT = 600
